"""Initial migration for TCG core tables

Revision ID: c04acb195045
Revises: 
Create Date: 2026-03-03 00:14:46.982307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04acb195045'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(length=3), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_table('grand_prix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('season_half', sa.Integer(), nullable=True),
    sa.Column('fp1_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fp2_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fp3_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('squaly_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sprint_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qualy_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('race_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('has_sprint', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grand_prix_id'), 'grand_prix', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('player', 'admin', name='userrole'), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('assignments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('gp_id', sa.Integer(), nullable=False),
    sa.Column('acquired_method', sa.Enum('pack_opening', 'wildcard_swap', 'stolen', name='acquiredmethod'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['gp_id'], ['grand_prix.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'gp_id', name='_driver_gp_uc')
    )
    op.create_index(op.f('ix_assignments_id'), 'assignments', ['id'], unique=False)
    op.create_table('race_results',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gp_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('race_pos', sa.Integer(), nullable=False),
    sa.Column('race_points', sa.Integer(), nullable=True),
    sa.Column('sprint_pos', sa.Integer(), nullable=True),
    sa.Column('sprint_points', sa.Integer(), nullable=True),
    sa.Column('gp_points', sa.Integer(), nullable=True),
    sa.Column('is_dnf', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['gp_id'], ['grand_prix.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_race_results_id'), 'race_results', ['id'], unique=False)
    op.create_table('wildcard_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gp_id', sa.Integer(), nullable=False),
    sa.Column('wildcard_type', sa.Enum('pre_race_swap', 'post_race_swap', 'random_swap', 'steal', name='wildcardtype'), nullable=False),
    sa.Column('season_half', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['gp_id'], ['grand_prix.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'gp_id', name='_user_gp_wildcard_uc'),
    sa.UniqueConstraint('user_id', 'wildcard_type', 'season_half', name='_user_wildcard_half_uc')
    )
    op.create_index(op.f('ix_wildcard_usage_id'), 'wildcard_usage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wildcard_usage_id'), table_name='wildcard_usage')
    op.drop_table('wildcard_usage')
    op.drop_index(op.f('ix_race_results_id'), table_name='race_results')
    op.drop_table('race_results')
    op.drop_index(op.f('ix_assignments_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_grand_prix_id'), table_name='grand_prix')
    op.drop_table('grand_prix')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
